### Create EC2 Instances and Node Configurations

- name: Spin up EC2 Instances
  hosts: localhost
  gather_facts: True
  vars_files:
    - ansible_vars.yml
  tags:
    - launch
  tasks:
    - name: Launch Kadena Server Instances
      ec2:
        key_name: "{{ instance_key_name }}"
        group: "{{ instance_security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ instance_image }}"
        wait: true
        wait_timeout: 500
        region: "{{ instance_region }}"
        monitoring: no
        instance_tags:
          Name: kadena_server
        exact_count: 4
        count_tag:
          Name: kadena_server
      register: ec2_servers_out

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items:
        - "{{ ec2_servers_out.instances }}"

    - name: Refresh EC2 cache
      command: /etc/ansible/ec2.py --refresh-cache
    - name: Refresh in-memory EC2 cache
      meta: refresh_inventory

- name: Create node configurations
  hosts: localhost
  gather_facts: False
  vars_files:
    - ansible_vars.yml
  vars:
    ipList: "{{ hostvars[inventory_hostname].groups.tag_Name_kadena_server }}"
  tasks:
    - name: Create 'conf' directory to store nodes' configuration file 
      file:
        path: "{{ conf_path }}/conf/"
        state: directory
        mode: 0755

    - name: Clean up Configuration Files
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "{{ conf_path }}/conf/*"
        - ipAddr.yml

    - name: Create file of Kadena server(s)' IP addresses
      template:
        src: templates/ipAddr.j2
        dest: ipAddr.yml
        mode: 0777

    - name: Generate default node configuration for the Kadena servers
      shell: yes '' | "{{ bin_path | expanduser }}"/genconfs --distributed "{{ playbook_dir }}"/ipAddr.yml
      args:
        chdir: "{{ conf_path }}"

- name: Configure instance(s)
  hosts: tag_Name_kadena_server
  become: True
  gather_facts: False
  vars_files:
    - ansible_vars.yml
  tasks:
    - name: Create log directory in server nodes
      file:
        path: log/
        state: directory
        mode: 0755

    - name: Copy node conf file to server
      copy:
        src: "{{ conf_path }}/conf/{{inventory_hostname}}-cluster.yaml"
        dest: conf-cluster.yaml

    - name: Copy `kadenaserver` executable to server
      copy:
        src: "{{ bin_path }}/kadenaserver"
        dest: kadenaserver
        mode: a+x
